version: 2

sources:
  - name: stg_jaffle_shop
    description: jaffle shop raw data
    database: jaffle_shop
    schema: public
    tables:
      - name: payments
      - name: orders
      - name: customers
        